version: '3'
services:
  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - './elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml'
      - elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
      discovery.type: single-node
    networks:
      - elk

  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - './logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml'
      - './logstash/pipeline:/usr/share/logstash/pipeline'
      - log-data
    ports:
      - "5000:5000"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - './kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml'
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  app:
    build:
      context: .
      dockerfile: containers/app/Dockerfile
    command: bash -c "rake assets:precompile db:create db:migrate && cp -f ./app/assets/statics/* ./public/ && pumactl -F ./containers/app/puma.rb start"
    volumes:
      - .:/webapp:cached
      - public-data:/webapp/public
      - tmp-data:/webapp/tmp
      - log-data:/webapp/log
    depends_on:
      - db
      - redis
    ports:
      - 3000:3000
    tty: true
    stdin_open: true

  db:
    restart:
      always
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=passw0rd
    volumes:
      - ./containers/mysql/my.cnf:/etc/mysql/my.cnf
      - db-data:/var/lib/mysql
    ports:
      - 43306:3306

  redis:
    restart:
      always
    image: redis:5.0
    ports:
      - 16379:6379

networks:
  elk:
    driver: bridge

volumes:
  public-data:
  tmp-data:
  log-data:
  db-data:
  elasticsearch:
